spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/movie
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: emVyb2Jhc2Utc3ByaW5nLWJvb3QtcHJvamVjdC1qd3Qtc2VjcmV0LWtleQo=

